apiVersion: v1
kind: Pod
metadata:
  name: new-pod
  labels:
    app: testing
spec:
  containers:
    - name: new-container
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80

